set(UTILS_TARGET utils)

file(GLOB SOURCES CONFIGURE_DEPENDS *.cpp)
file(GLOB HEADERS CONFIGURE_DEPENDS *.h)

add_library(${UTILS_TARGET} STATIC
	${SOURCES}
	${HEADERS}
)

set_target_properties(${UTILS_TARGET} PROPERTIES LINKER_LANGUAGE CXX)

target_include_directories(${UTILS_TARGET}
	PUBLIC
		${CMAKE_CURRENT_LIST_DIR}
)
